### PR TITLE
Add use eager loader only for first row

### PR DESCRIPTION
**Pull request by emiliogrv**
Hi, this PR solve the multiple loads when you have many belongsTo relationships in many lines within a row component:

Also remove mb-3 to belongsTo fields to solve it:

### CODE REVIEW

**Comment by disitec** [comment]
Maybe I misunderstood the PR but Im still doing a call with every row. Can you check this? Thanks.

image

**Comment by disitec** [comment]
Also, for code style. Can you use `@data-set-available` for the event and avoid using switch cases with only one option? (I thin a `if` fits better)

Than you.

**Comment by emiliogrv** [comment]
Hi @disitec I changed the name of the event and replaced the switch case by an if

The PR is for make less requests to the server, only making request for the first row, I leave a gif that how this found and code with I test
ezgif com-video-to-gif 1

```php
use R64\NovaFields\BelongsTo as CustomBelongsTo;
use R64\NovaFields\Number as CustomNumber;
use R64\NovaFields\Row;
use R64\NovaFields\Text as CustomText;
```
...

```php
            Row::make('Líneas',
                [
                    CustomNumber::make('Cantidad', 'quantity')
                        ->fieldClasses('w-full p-1')
                        ->hideLabelInForms()
                        ->min(1)
                        ->rules(
                            'required',
                            'integer',
                            'min:1'
                        )
                        ->sortable(),

                    CustomText::make('Precio', 'price')
                        ->fieldClasses('w-full p-1')
                        ->hideLabelInForms()
                        ->rules(
                            'required',
                            'string',
                            'regex:/^\d+((,|\.)\d{1,2})?$/'
                        )
                        ->sortable(),

                    /**
                     * Relationships
                     */
                    CustomBelongsTo::make('Producto', 'product', Product::class)
                        ->fieldClasses('w-full p-1')
                        ->hideLabelInForms(),
                ],
                'lines'
            )
                ->fieldClasses('w-full px-8 py-6')
                ->onlyOnForms(),
```

**Comment by disitec** [comment]
This will be available in 0.6.4 🎉

**Pull request merged**
