### PR TITLE
row field validation support

### PR DESCRIPTION
**Pull request by pehbehbeh**
This adds basic validation for the row field.

For transmitting data we also changed the implementation to using form data (like the JSON field) instead of a JSON string.

Here is a screenshot of an error message:

image

### CODE REVIEW

**Comment by PKuebler** [comment]
Usecase:

```
Row::make(__('models/langitem.title.plural'), collect([
         ...
         Text::make(__('models/contract_item.attributes.rrp'), 'rrp')
             ->rules('required', 'numeric'),
]), 'masked_contract_items')
```

**Comment by pehbehbeh** [comment]
With https://github.com/sourceboat/nova-fields/pull/2 @PKuebler also added support for rules on the row-field itself. 👍

**Comment by disitec** [comment]
Thank you guys!

**Comment by disitec** [comment]
This closes #30

**Comment by sabid** [comment]
Hello @pehbehbeh and @PKuebler , thanks for your great work, whih the validation.

The following error appears in my form.

row sub-fileds validation


When the validation is done, it shows the errors of the all form, from the beginning.
It seems that the fields that are valid are not filtered by the "ROW" fields
It should show the field errors "ROW". (Sub-fields)

The field that has an error in the validation could also be shown in red

**Comment by PKuebler** [comment]
hey @sabid, 

we fix it today.

**Pull request merged**
