### PR TITLE
Fix Rule generation for HasChilds fields

### LINKED ISSUE #133: [BUG] Nova 2.5.0 Required Rule issue
When updated to Nova 2.5.0, this fields fails to be handled properly as the new `isRequired` addition. This makes any form pages with this field on it unable to load.
The issue is the rules are generated like:

    array:4 [
      "name_extension." => []
      "name_extension.original" => []
      "name_extension.addition" => array:2 [
        0 => "nullable"
        1 => "max:50"
      ]
      "name_extension.condition" => []
    ]

instead of:

    array:4 [
      "name_extension" => []
      "name_extension.original" => []
      "name_extension.addition" => array:2 [
        0 => "nullable"
        1 => "max:50"
      ]
      "name_extension.condition" => []
    ]

This causes the new "required" check to fail with "undefined index" as it looks for `name_extension` and not `name_extension.`

The temporary fix I had, which I was going to submit as a PR asap, unless someone fixes it sooner is just checking the key like (L170 of JSON.php):
`return [$this->attribute . ($key ? '.' . $key : '') => $rules];`
so that the non-suffixed key exists as nova is expecting.

### PR DESCRIPTION
**Pull request by ragingdave**
fixes #133

### CODE REVIEW

**Comment by disitec** [comment]
Gonna take a look today to the pending PR and fixes. Thanks guys!

**Comment by dtannen** [comment]
@disitec @ragingdave for some reason this breaks the use of the Row field in a Nova action.  Can you please check this?

**Comment by disitec** [comment]
@dtannen will do.

**Comment by disitec** [comment]
@dtannen as i can see. Row methods has been just copied to the trait. There are no changes at all. Can you share the error you are getting?

**Comment by dtannen** [comment]
@disitec ok-- maybe it's separate and unrelated to this issue.  Please try to add a Row as a field in a action using Nova 2.5.  When clicking on the action -- it just hangs.

**Pull request merged**
