### PR TITLE
added dependsOn and prepopulate features and fixed nullable 

### PR DESCRIPTION
**Pull request by gaabora**
Now you can define dependent fields
on each update of fields listed in `->dependsOn(['field'])`
list of dependent field options will rebuild.

Usage example:
```
BelongsTo::make('City'),

BelongsTo::make('Office')
	->nullable()

	->dependsOn(['city'])
	->setRelatableParams(['city' => $this->city_id]) // also compatible with ->quickCreate(['city' => ['belongsToId' => $this->city_id,'readOnly' => true]])
	
	// to prepopulate searchable
	->searchable()
	->prepopulate(['take'=>5,'orderBy' => ['created_at' => 'desc']])
,
```
in order to dependsOn to work you also need to set `relatableQuery()` method in your related resource
```
class Office extends Resource
{
    public static function relatableQuery( $request, $query)
    {
        $relatableParams = json_decode($request->input('relatableParams'));
        if ($relatableParams) {
            if ($request->route('resource') == 'cities') {
                if (property_exists($relatableParams, 'city')) {
                    $query = $query->where('city_id', $relatableParams->city);
                }
            }
        }
        
        return $query;
    }
}
```

Troubleshooting:

If nullable BelongsTo still gives "This may not be associated with this resource"
https://github.com/laravel/nova-issues/issues/1661

then fix vendor code manually
```
namespace Laravel\Nova\Rules;
class Relatable implements Rule
...
public function passes($attribute, $value)
    {
        if ($value === null) return true; // add this.
...
```

### CODE REVIEW

**Comment by gaabora** [comment]
Also clearSelection() for searchable now works as intended.

**Comment by gaabora** [comment]
Hello @disitec
I added some nice features to package.
Do you plan to merge this in near time?

**Comment by disitec** [comment]
Hi @gaabora excellent work! Sorry for the delay, I was on vacation last copule of weeks.

Of course I plan to merge this feature you are working on. If is still in progress, please feel free to add as much as you need.

Regarding to the dependency container it is a great idea to have one here without external libraries so we could mantain it in the future.

Thanks for your time.

**Comment by gaabora** [comment]
Job's done tho.
- added mask() and raw() to Text field. (Thanks to wemersonrv/input-mask)
- added flexible dependency container based on [abandoned?] epartment/nova-dependency-container


usage examples:
```
Text::make( __('Phone'),  'phone')
    ->mask('# (###) ###-##-##') // 1 (234) 567-89-10
    ->raw() // to save raw value ("12345678910" instead of "1 (234) 567-89-10")
    ->sortable()
,
```
and
```

BelongsTo::make('SomeParam', 'some_param', SomeParam::class)
    ->nullable()
    ->sortable()
,
DependencyContainer::make([
    Text::make('SomeField'),
    BelongsTo::make('OtherField'),
])->dependsOn('some_param', 123)
    ->setWatchable('selectedResource','value') // !required line if depends on BelongsTo
,
```
Maybe someone discover some bugs (if there are) in future.

**Comment by gaabora** [comment]
As of 2.0.8 updates broke most of marketplace plugins I need an advice of how to contribute for this plugin's 2.0.8 compatible branch. @disitec 
For now i notice a change in /nova-api/companies/creation-fields response structure: fields now nested in fields attribute of JSON response so
in ModalCreate.vue async getFields() method now must be
`fields.**fields**.forEach((field, key) => {`
and same in ModalUpdate.vue 
`this.fields = fields.**fields**;`

but quickCreate() modal wont work for some weird reason (while quickEdit works well):
`[Vue warn]: Unknown custom element: <form-undefined> `

**Comment by gaabora** [comment]
added ability to set parent resource uriKey for BelongsTo 
when using BelongsTo inside a Row or JSON field
for example on some resource (not City nor Office) that do not have a city() attribute
```
Row::make('data', [
    BelongsTo::make('City')
        ->withMeta(['resourceUriKey'=>'offices']) // if Office model has a city() field
```

**Comment by gaabora** [comment]
Waiting for merge so I can make a new PR with another features and some refactoring.

**Pull request closed without merging**
